# Generated by Django 5.2.3 on 2025-08-03 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('num_players', models.IntegerField(default=4)),
                ('players_data', models.TextField(default='[]')),
                ('current_player', models.IntegerField(default=1)),
                ('desk_cards', models.TextField(default='{}')),
                ('is_game_started', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('winner_player_num', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('disconnected_player', models.IntegerField(blank=True, null=True)),
                ('reconnect_timer_start', models.DateTimeField(blank=True, null=True)),
                ('terminated_due_to_disconnect', models.BooleanField(default=False)),
                ('game_scores', models.TextField(default='{}')),
            ],
        ),
    ]
